config/routes.rb
Wallstickers::Application.routes.draw do
  root :to => 'pages#home'

  controller :pages do
    get 'about',    :to => :about,    :as => :about_page
    get 'contact',  :to => :contact,  :as => :contact_page
    get 'delivery', :to => :delivery, :as => :delivery_page
    get 'how-to',   :to => :how_to,   :as => :how_to_page
    get 'lost',     :to => :lost,     :as => :lost_page
    get 'privacy',  :to => :privacy,  :as => :privacy_page
    get 'returns',  :to => :returns,  :as => :returns_page
    get 'rules',    :to => :rules,    :as => :rules_page
  end

  controller :user_sessions do
    get 'logout',         :to => :destroy,  :as => :logout
    post 'user_sessions', :to => :create
  end

  get 'browse/:id', :to => 'categories#browse', :as => 'browse_category'

  controller :shopping_cart do
    get  'cart',             :to => :shopping_cart, :as => 'shopping_cart'
    post 'cart/checkout',   :to => :checkout, :as => 'shopping_cart_checkout'
  end

  # TODO: temporary
  get  '/orders', :to => 'order_processing#printer_orders',  :as => 'printer_orders'

  scope :path => '/order', :controller => :order_processing do
    get  ':id' => :show,   :as => 'show_order_progress'
    post ':id' => :update, :as => 'update_order_progress'
  end

  get  'register', :to => 'profiles#new',    :as => 'register_user'
  post 'register', :to => 'profiles#create', :as => 'create_user'

  scope :path => '/profile', :controller => :profiles do
    get  ':id',      :to => :profile, :as => 'profile'
    get  ':id/edit', :to => :edit,    :as => 'edit_profile'
    put  ':id/edit', :to => :update,  :as => 'update_profile'
    get  ':id/register-artist', :to => :register_artist, :as => 'register_artist'
    post ':id/register-artist', :to => :create_artist,   :as => 'create_artist'
  end

  WALLSTICKER_PERMALINK_REGEXP = /[[:alnum:]]+\/[a-zA-Z0-9_+%-]+/
  controller :wallstickers do
    get  ':artist',              :to => :gallery,     :as => 'artist_gallery'
    get  ':artist/new',          :to => :new,         :as => 'new_wallsticker'
    post ':artist/new',          :to => :create,      :as => 'create_wallsticker'
    get  ':artist_title',        :to => :show,        :as => 'show_wallsticker',
         :constraints => { :artist_title => WALLSTICKER_PERMALINK_REGEXP }
    post ':artist_title/order',  :to => :add_to_cart, :as => 'add_wallsticker_to_cart',
         :constraints => { :artist_title => WALLSTICKER_PERMALINK_REGEXP }
    get  ':artist_title/order',  :to => redirect { |p| "/#{p[:artist_title]}" },
         :constraints => { :artist_title => WALLSTICKER_PERMALINK_REGEXP }
  end

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/controllers/order_processing_controller.rb
class OrderProcessingController < ApplicationController
  before_filter :find_order, :except => [:printer_orders]

  def printer_orders
    # TODO: better permissions / authorize!
    raise not_found unless current_user.printer?

    @printer = current_user.printer
    @publisher = @printer.publisher

    @pending_orders = @publisher.pending_orders
    @current_orders = @publisher.current_orders
    @finished_orders = @publisher.finished_orders
  end

  def show
    authorize! :show_order_process, @order

    case @order.status
    when :waiting_confirm_address_info
      @order.billing_address  = Address.new
      @order.shipping_address = Address.new
    end

    render_status_page(@order.status)
  end

  def update
    authorize! :update_order_process, @order

    unless params[:update_status] == @order.status.to_s
      fail "Mismatched controller state: #{params[:update_status]} vs #{@order.status}"
    end

    if :waiting_confirm_address_info == @order.status
      # TODO: limit params to :billing_address_attributes and :shipping_address_attributes
      # TODO: make shipping_address form optional!
      @order.update_attributes(params[:order])
    end

    case @order.status
    when :waiting_redirect_to_payment_gateway
      @order.level_up!
      @order.level_up!  # TODO - callback + verification
      redirect_to show_order_progress_path(@order)
    else
      if @order.can_level_up?
        @order.level_up!
        redirect_to show_order_progress_path(@order)
      else
        render_status_page(@order.status)
      end
    end
  end

  private

    def find_order
      @order = Order.find_by_token(params[:id]) || not_found
    end

    def render_status_page(status)
      status = status.to_s
      if status.start_with?('waiting_')
        render status.sub('waiting_', '')
      elsif 'finished' == status
        render 'finished'
      else
        fail 'Missing status: #{status}'
      end
    end
end

app/views/order_processing/acceptance_by_printer.html.erb
<% if can? :show_order_process, @order %>
  Order Status: <%= @order.status_name %>
<% end %>


<% if can? :update_order_process, @order %>
  Please confirm this Printing Order:

  <%= form_for @order, :url => update_order_progress_path, :method => :post do |form| %>
    <%= hidden_field_tag 'update_status', 'waiting_acceptance_by_printer' %>
    <%= form.submit 'Accept print order' %>
  <% end %>
<% end %>

app/views/order_processing/complete_printing.html.erb
<% if can? :show_order_process, @order %>
  Order Status: <%= @order.status_name %>
<% end %>

<% if can? :update_order_process, @order %>
  <p>Items to be printed:</p>

  <table style='border-spacing:10px;'>
  <% @order.order_items.each do |item| %>
  <tr>
    <td><%= link_to 'Download source image', item.variant.wallsticker.source_image_url %></td>
    <td><%= item.variant.wallsticker.title %></td>
    <td><%= "#{item.variant.width_cm}x#{item.variant.height_cm} cm" %></td>
  </tr>
  <% end %>
  </table>

  <p>Please confirm printing is completed:</p>

  <%= form_for @order, :url => update_order_progress_path, :method => :post do |form| %>
    <%= hidden_field_tag 'update_status', 'waiting_complete_printing' %>
    <%= form.submit 'Printing complete!' %>
  <% end %>
<% end %>

app/views/order_processing/confirm_address_info.html.erb
Great! We just need your billing and shipping info.

<%= semantic_form_for @order,
                      :url => update_order_progress_path,
                      :method => :post do |f| %>

  <%= hidden_field_tag 'update_status', 'waiting_confirm_address_info' %>

  <h3>Billing Address</h3>
  <%= f.inputs :for => :billing_address do |a| %>
    <%= a.inputs :street_line, :zipcode, :city %>

    <select><option>Poland</option></select>
  <% end %>

  <h3>Shipping Address</h3>
  <%= f.inputs :for => :shipping_address do |a| %>
    <%= a.inputs :street_line, :zipcode, :city %>

    <select><option>Poland</option></select>
  <% end %>

  <%= f.buttons do %>
    <%= f.commit_button 'Confirm Address' %>
  <% end %>

<% end %>

app/views/order_processing/finished.html.erb
TODO - view!

This order was successfully completed and shipped.

app/views/order_processing/printer_orders.html.erb
<h2>New Orders:</h2>

<% @pending_orders.each do |order| %>
  <p><%= link_to "Order #{order.token} (#{order.balance_pln} PLN)", show_order_progress_path(order) %></p>

  <table style='border-spacing:10px;'>
    <% order.order_items.each do |item| %>
      <tr>
        <td><%= item.variant.wallsticker.title %></td>
        <td><%= "#{item.variant.width_cm}x#{item.variant.height_cm} cm" %></td>
      </tr>
    <% end %>
  </table>
<% end %>


<h2>Current Orders:</h2>
<% @current_orders.each do |order| %>
  <p><%= link_to "Order #{order.token}",
         show_order_progress_path(order) %>
    - <%= order.status.to_s.humanize %>
  </p>

  <table style='border-spacing:10px;'>
    <% order.order_items.each do |item| %>
      <tr>
        <td><%= link_to 'Download source image', item.variant.wallsticker.source_image_url %></td>
        <td><%= item.variant.wallsticker.title %></td>
        <td><%= "#{item.variant.width_cm}x#{item.variant.height_cm} cm" %></td>
      </tr>
    <% end %>
  </table>
<% end %>


<h2>Finished Orders:</h2>
<% @finished_orders.each do |order| %>
  <p><%= link_to "Order #{order.token} (#{order.balance_pln} PLN)", show_order_progress_path(order) %></p>

  <table style='border-spacing:10px;'>
    <% order.order_items.each do |item| %>
      <tr>
        <td><%= item.variant.wallsticker.title %></td>
        <td><%= "#{item.variant.width_cm}x#{item.variant.height_cm} cm" %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/order_processing/redirect_to_payment_gateway.html.erb
TODO - view!

Confirm your purchase, Choose your payment gateway, and Click submit
to be redirected to payment gateway.

<%= form_for @order, :url => update_order_progress_path, :method => :post do |form| %>
  <%= hidden_field_tag 'update_status', 'waiting_redirect_to_payment_gateway' %>
  <%= form.submit 'Let me pay!' %>
<% end %>

app/views/order_processing/shipping_package.html.erb
<% if can? :show_order_process, @order %>
  Order Status: <%= @order.status_name %>
<% end %>

<% if can? :update_order_process, @order %>
  Please confirm order has been shipped:

  <%= form_for @order, :url => update_order_progress_path, :method => :post do |form| %>
    <%= hidden_field_tag 'update_status', 'waiting_shipping_package' %>
    <%= form.submit 'Package shipped!' %>
  <% end %>
<% end %>