config/routes.rb
Wallstickers::Application.routes.draw do
  root :to => 'pages#home'

  controller :pages do
    get 'about',    :to => :about,    :as => :about_page
    get 'contact',  :to => :contact,  :as => :contact_page
    get 'delivery', :to => :delivery, :as => :delivery_page
    get 'how-to',   :to => :how_to,   :as => :how_to_page
    get 'lost',     :to => :lost,     :as => :lost_page
    get 'privacy',  :to => :privacy,  :as => :privacy_page
    get 'returns',  :to => :returns,  :as => :returns_page
    get 'rules',    :to => :rules,    :as => :rules_page
  end

  controller :user_sessions do
    get 'logout',         :to => :destroy,  :as => :logout
    post 'user_sessions', :to => :create
  end

  get 'browse/:id', :to => 'categories#browse', :as => 'browse_category'

  controller :shopping_cart do
    get  'cart',             :to => :shopping_cart, :as => 'shopping_cart'
    post 'cart/checkout',   :to => :checkout, :as => 'shopping_cart_checkout'
  end

  # TODO: temporary
  get  '/orders', :to => 'order_processing#printer_orders',  :as => 'printer_orders'

  scope :path => '/order', :controller => :order_processing do
    get  ':id' => :show,   :as => 'show_order_progress'
    post ':id' => :update, :as => 'update_order_progress'
  end

  get  'register', :to => 'profiles#new',    :as => 'register_user'
  post 'register', :to => 'profiles#create', :as => 'create_user'

  scope :path => '/profile', :controller => :profiles do
    get  ':id',      :to => :profile, :as => 'profile'
    get  ':id/edit', :to => :edit,    :as => 'edit_profile'
    put  ':id/edit', :to => :update,  :as => 'update_profile'
    get  ':id/register-artist', :to => :register_artist, :as => 'register_artist'
    post ':id/register-artist', :to => :create_artist,   :as => 'create_artist'
  end

  WALLSTICKER_PERMALINK_REGEXP = /[[:alnum:]]+\/[a-zA-Z0-9_+%-]+/
  controller :wallstickers do
    get  ':artist',              :to => :gallery,     :as => 'artist_gallery'
    get  ':artist/new',          :to => :new,         :as => 'new_wallsticker'
    post ':artist/new',          :to => :create,      :as => 'create_wallsticker'
    get  ':artist_title',        :to => :show,        :as => 'show_wallsticker',
         :constraints => { :artist_title => WALLSTICKER_PERMALINK_REGEXP }
    post ':artist_title/order',  :to => :add_to_cart, :as => 'add_wallsticker_to_cart',
         :constraints => { :artist_title => WALLSTICKER_PERMALINK_REGEXP }
    get  ':artist_title/order',  :to => redirect { |p| "/#{p[:artist_title]}" },
         :constraints => { :artist_title => WALLSTICKER_PERMALINK_REGEXP }
  end

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/_bottom.html.erb
<section id="bottomNav">
  <ul>
    <li class="hasTitle"><h3><%= t 'layouts.bottom.stickers.title' %></h3></li>
    <li><%= link_to t('layouts.bottom.stickers.about'), about_page_path %></li>
    <li><%= link_to t('layouts.bottom.stickers.conditions'), rules_page_path %></li>
    <li><%= link_to t('layouts.bottom.stickers.privacy'), privacy_page_path %></li>
    <li>
      <% if current_user %>
        <%= link_to t('layouts.bottom.stickers.design'), new_wallsticker_path(current_user) %>
      <% else %>
        <%= link_to t('layouts.bottom.stickers.design'), register_user_path %>
      <% end %>
    </li>
    <li><%= link_to t('layouts.bottom.stickers.contact'), contact_page_path %></li>
  </ul>
  <ul>
    <li class="hasTitle"><h3><%= t 'layouts.bottom.shopping.title' %></h3></li>
    <li><%= link_to t('layouts.bottom.shopping.delivery'), delivery_page_path %></li>
    <li><%= link_to t('layouts.bottom.shopping.returns'), returns_page_path %></li>
    <li><%= link_to t('layouts.bottom.shopping.tracking'), lost_page_path %></li>
  </ul>
  <ul>
    <li class="hasTitle"><h3><%= t 'layouts.bottom.qna.title' %></h3></li>
    <li><%= link_to t('layouts.bottom.qna.how_to'), how_to_page_path %></li>
  </ul>
</section>

app/views/layouts/_daily_artist.html.erb
  <div class="floatRow clearAfter">
    <section id="authorsDetails">
      <h2><%= t 'layouts.artist_of_the_day.title' %></h2>

      <%= image_tag(@promoted_artist.avatar_url, :class => 'avatar') %>

      <div class="authorDescription">
        <h3>
          <%= link_to @promoted_artist.full_name, artist_gallery_path(@promoted_artist) %>
        </h3>
        <ul>
          <li><%= t 'layouts.artist_of_the_day.since' %>:
            <strong><%= l(@promoted_artist.created_at, :format => :short) %></strong>
          </li>
          <li><%= t 'layouts.artist_of_the_day.designed'%>:
            <%= link_to artist_gallery_path(@promoted_artist) do %>
              <%= @promoted_artist.wallstickers.count.to_s %>
            <% end %>
          </li>
        </ul>
        <a href="<%= artist_gallery_path(@promoted_artist) %>" class="button" id="goToGallery">
          <%= t 'layouts.artist_of_the_day.gallery' %>
        </a>
      </div>
    </section>

    <section id="authorsGallery">
      <% @promoted_artist.wallstickers.each do |wallsticker| %>
        <%= link_to show_wallsticker_path(wallsticker) do %>
          <%= image_tag wallsticker.small_square_image_url, :alt => 'miniaturka' %>
        <% end %>
      <% end %>
    </section>

    <section id="ctaContainer">
      <% if current_user %>
        <%= link_to new_wallsticker_path(current_user), :class => "cta" do %>
          <h2><%= t 'layouts.cta.title' %></h2>
          <p><span><%= t 'layouts.cta.join' %></span></p>
          <span><%= t 'layouts.cta.create' %></span>
        <% end %>
      <% else %>
        <%= link_to register_user_path, :class => "cta" do %>
          <h2><%= t 'layouts.cta.title' %></h2>
          <p><span><%= t 'layouts.cta.join' %></span></p>
          <span><%= t 'layouts.cta.create' %></span>
        <% end %>
      <% end %>

      </a>
    </section>
  </div>

app/views/layouts/_head.html.erb
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">

    <%= stylesheet_link_tag 'application' %>
    <!--[if IE]><%= stylesheet_link_tag 'ie' %><![endif]-->
    <!--[if lt IE 7]><%= stylesheet_link_tag 'ie6' %><![endif]-->

    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <title>Wallstickers.pl</title>
</head>

app/views/layouts/_header.html.erb
<header>
  <%= link_to t('layouts.back_to_homepage.text'), root_path,
      :id => "homeLink", :title => t('layouts.back_to_homepage.title') %>
  <section class="rFloated">
    <% if current_user %>
      <%= link_to t('layouts.user.account'), profile_path(current_user) %>
      <em class="sep">|</em>
      <%= link_to t('layouts.user.logout'), :logout %>
    <% else %>

      <%= form_tag user_sessions_path, :method => :post, :id => 'session' do %>
        <fieldset>
          <input type="text" name="username" value="Login"
                 onfocus="if (this.value=='Login') this.value=''"
                 onblur="if (this.value=='') this.value='Login'" >
          <input type="password" name="password" value="Password"
                 onfocus="if (this.value=='Password') this.value=''"
                 onblur="if (this.value=='') this.value='Password'" >
          <input type="submit" value="Login" >
        </fieldset>
        <fieldset id="opts">
          <%= link_to t('layouts.user.remind_password'), '#' %><!-- TODO -->
          <em class="sep">|</em>
          <%= link_to t('layouts.user.register'), register_user_path %>
        </fieldset>
      <% end %>

    <% end %>

    <div id="cartInfoBar">
      <%= link_to t('layouts.user.goto_cart'), :shopping_cart, :id => 'goToCart' %>
      <span id="cartsItemCounter"><%= current_user_shopping_cart_item_count %></span>
      <em class="sep">|</em>
      <%= link_to t('layouts.user.view_cart'), :shopping_cart %>
    </div>
  </section>
</header>

app/views/layouts/_howto.html.erb
<section id="howtoBox">
  <div class="boxContent">
    <h2><%= t 'layouts.how_to.how'%></h2>
    <p>
      <%= t 'layouts.how_to.how_text'%>
    </p>
    <hr>
    <h2><%= t 'layouts.how_to.problems'%></h2>
    <p>
      <%= t 'layouts.how_to.problems_text'%>
    </p>
    <ul id="contactInfo">
      <li id="phoneInfo"><%= t 'layouts.contact.phone'%></li>
      <li id="emailInfo"><%= t 'layouts.contact.email'%></li>
    </ul>
  </div>
</section>

app/views/layouts/_newsletter.html.erb
<div id="subsBox" class="contentBox transparentBox">
  <section id="newsletterBox">
    <h2><%= t 'layouts.newsletter.title' %> <em><%= t 'layouts.newsletter.newsletter' %></em></h2>
    <form action="/subscribe" method="post">
      <fieldset>
        <input type="text" value="<%= t 'layouts.newsletter.email' %>"
               onfocus="this.value=''"
        >
        <input type="submit" value="<%= t 'layouts.newsletter.subscribe' %>">
        <input type="button" value="<%= t 'layouts.newsletter.unsubscribe' %>">
      </fieldset>      
    </form>
  </section>
  <section id="facebookBox">
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) {return;}
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/pl_PL/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    </script>
    <h2><%= t 'layouts.like_us' %> <em><%= t 'layouts.facebook' %></em></h2>
    <div class="fb-facepile" data-href="wallstickers.pl" data-width="520" data-max-rows="1"></div>
  </section>
</div>

app/views/layouts/_notices.html.erb
<!-- TODO: notices -->
<div id='user_notices'>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

app/views/layouts/_search.html.erb
<section id="searchBar">
  <div>
    <h4><%= t 'pages.home.search_bar.title' %></h4>
    <p><%= t 'pages.home.search_bar.call' %> <em><%= t 'pages.home.search_bar.phone_number' %></em></p>
  </div>
  <form action="/serach/" method="post">
    <fieldset>
      <input type="text">
      <input type="submit" value="szukaj">
    </fieldset>
  </form>
</section>

app/views/layouts/_social.html.erb
<section id="socialBox">
    <h2><%= t 'layouts.social.follow' %></h2>
    <ul>
      <li><a href="#" id="twitter" class="socialLogotype">Twitter</a></li>
      <li><a href="#" id="flaker" class="socialLogotype">Flaker</a></li>
      <li><a href="#" id="blip" class="socialLogotype">Blip</a></li>
    </ul>
    <h2><%= t 'layouts.social.see' %></h2>
    <ul>
      <li><a href="#" id="flickr" class="socialLogotype">Fickr</a></li>
      <li><a href="#" id="youtube" class="socialLogotype">Youtube</a></li>
    </ul>
</section>

app/views/layouts/_update.html.erb
<div id="updateBrowser">
    <h2>
      <%= t 'layouts.update_browser.shout' %>  <%= l(Date.today, :format => "%Y") %>!
      <%= t 'layouts.update_browser.explorer' %>
    </h2>
    <p>
      <%= t 'layouts.update_browser.message' %>
    </p>
    <ul>
      <li>&raquo; <a id="bie" href="http://www.microsoft.com/poland/twojanowa/default.aspx" title="Zaktualizuj Internet Explorera">Internet Explorer 9.0</a></li>
      <li>&raquo; <a id="bfirefox" href="http://firefox.pl" title="Pobierz Firefoksa">Mozilla Firefox</a></li>
      <li>&raquo; <a id="bchrome" href="http://google.pl/chrome" title="Pobierz Chromę">Google Chrome</a></li>
      <li>&raquo; <a id="bopera" href="http://opera.com" title="Pobierz Operę">Opera</a></li>
      <li>&raquo; <a id="bsafari" href="http://apple.com/pl/safari" title="Pobierz Safari">Safari</a></li>
    </ul>
    <p><%= t 'layouts.update_browser.return' %></p>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir="ltr" lang="<%= t 'layouts.language' %>">
  <%= render 'layouts/head' %>

  <body class="<%= body_classes.join(' ') %>">
    <div id="wrapper">

      <% if current_user %>
        <%= link_to new_wallsticker_path(current_user), :class => "cta createSticker" do %>
          <% t 'layouts.design_a_sticker' %>
        <% end %>
      <% else %>
        <%= link_to register_user_path, :class => "cta createSticker" do %>
          <% t 'layouts.design_a_sticker' %>
        <% end %>
      <% end %>

      <%= render 'layouts/header' %>
      <%= render 'layouts/notices' %>

      <div class="contentBox hasShadow">
        <%= render 'layouts/search' %>
        <%= yield %>
      </div>

      <%= render 'layouts/newsletter' %>

      <div class="contentBox">

        <%= yield :promote %>

        <%= render 'layouts/social' %>
        <%= render 'layouts/bottom' %>

        <footer>
          <p>&copy; <%= t 'layouts.bottom.copyright' %></p>
        </footer>
      </div>

    </div>
    <%= render 'layouts/update' %>
  </body>
</html>